services:
  - type: web
    name: video-chat-backend
    env: node
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: video-chat-db
          property: connectionString
      - key: NODE_ENV
        value: production