services:
  - type: web
    name: video-chat-backend
    env: node
    buildCommand: npm install && npm run install:frontend && npm run build:frontend
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production